
services:
  ehrbase-postgres:
    image: ehrbase/ehrbase-v2-postgres:16.2
    container_name: ehrbase-postgres
    environment:
      POSTGRES_USER: postgres
      PASSWORD: postgres
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASSWORD: ehrbase_restricted
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASSWORD_ADMIN: ehrbase
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ehrbase-net

  ehrbase:
    image: ehrbase/ehrbase:latest  
    container_name: ehrbase
    depends_on:
      ehrbase-postgres:
        condition: service_healthy
    restart: on-failure # Añadido para mayor fiabilidad en el arranque
    environment:
      DB_URL: jdbc:postgresql://ehrbase-postgres:5432/ehrbase
      DB_USER: ehrbase_restricted
      DB_PASS: ehrbase_restricted
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      SERVER_NODENAME: local.ehrbase.org
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8081:8080" 
    networks:
      - ehrbase-net

networks:
  ehrbase-net:
    driver: bridge

